blog/urls.py
from django.urls import path

from .views import main, PostCreateView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('', main, name='main'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    '''Класс Поста'''
    title = models.CharField(max_length=255,verbose_name='Имя')
    img = models.ImageField(upload_to='posts/%Y/%m/%d/', verbose_name='Изобродение поста')
    content = RichTextUploadingField(verbose_name='Содержание')
    published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-published',]

blog/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView

from .models import Post

def main(request):
    '''Главная страница'''
    
    context = {
        'last_post': Post.objects.first(),
        'posts': Post.objects.all()[1:10]
    }
    return render(request, 'blog/main.html', context)

class PostCreateView(CreateView):
    '''Страница для создания нового поста'''

    model = Post
    template_name = 'blog/post_create.html'
    fields = ('title', 'img', 'content')

class PostDetailView(DetailView):
    '''Страница отдельного поста'''

    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

blog/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
    {% block style %}
    {% endblock style %}
</head>
<body>
    <!--Шапка-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
        <h5 class="my-0 ml-5 mr-md-auto font-weight-normal"><a id="logo" href="{% url 'blog:main' %}">Kodland <span id="black_text">Блог</span></a></h5>
        
        <a class="btn btn-primary btn-sm pl-3 pr-3" href="{% url 'blog:post_create' %}">+ Добавить статью</a>
    </div>

    <!--Контент-->  
    {% block content %}
    {% endblock content %}


    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/main.html
{% extends "_base.html" %}

{% load static %}

{% block title %}Главная{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock style %}

{% block content %}

    <!--Новая запись-->
    <div class="border-bottom shadow-sm">
        <div class="container mt-5 mb-5">
            <div class="row">
                <div class="col-7"><!--Содержание-->
                    <p><span id="new">NEW</span></p>
                    <h1>{{ last_post.title }}</h1>
                    <div id="last_post_content" class="mb-5">
                        <p>
                            {% autoescape off %}
                                {{ last_post.content | slice:":200" }}...
                            {% endautoescape %}
                        </p>
                    </div>
                    <p>
                        <a href="{{ last_post.get_absolute_url }}" class="btn btn-lg btn-primary">Читать</a>
                    </p>
                </div>


                <div class="col"><!--Изоброжение-->
                    <img id="last_post_img" src="{{ last_post.img.url }}" class=" rounded mx-auto d-block" />
                </div>
            </div>
        </div>
    </div>

    <!--Другие статьи-->
    <div id="posts" class=" mt-5 mb-5">
        <h2>Другие статьи</h2>

        <div class="mb-3 mt-4  row">
           {% for post in posts %}
                <div class=" post_item mb-4 ml-3 mr-5 border">
                    <a class="link" href="{{ post.get_absolute_url }}">
                        <div class="m-2 mb-3">
                            <div>
                                <span class="post_date">
                                {{ post.published|date:"d M Y H:i" }}
                                </span>
                            </div>
                            <div class="mt-1 mb-1">
                                <img  src="{{ post.img.url }}" class="img-thumbnail  mx-auto d-block post_img" />
                            </div>
                            <div class="text-center">
                                <h4>{{ post.title }}</h4>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            
          </div>
    </div>

{% endblock %}

blog/templates/blog/post_create.html
{% extends "_base.html" %}

{% load static %}

{% block title %}Добавить статью{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/post_create.css' %}">
{% endblock style %}

{% block content %}

    <div class="container mb-5">
        <h1 class="mt-5">Добавить статью</h1>

        <form enctype="multipart/form-data" method="post">
            <div >
                {% csrf_token %}
                {{ form.media }}

                <div class="row mb-4 mt-5">

                    <div class="col-9"><!--Title-->
                        <input type="text" class="form-control form-control-lg" placeholder="Введите название статьи" name="title" maxlength="255" required="" id="id_title">
                    </div>
                    <div class="col-3"><!--Button-->
                        <input id='submit' type="submit" class="btn btn-lg" value="Опубликовать">
                    </div>
                </div>

                <div class="row">

                    <!--Texarea-->
                    <div class="django-ckeditor-widget col-9" data-field-id="id_content" style="display: inline-block;">
                        <textarea cols="40" id="id_content" name="content" rows="10" required data-processed="0" 
                        data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;:
                             [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], 
                             &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, 
                             &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, 
                             &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, 
                             &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;,
                              &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], 
                              [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], 
                              &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, 
                                &quot;filebrowserWindowWidth&quot;: 940, 
                              &quot;filebrowserWindowHeight&quot;: 725, &quot;filebrowserUploadUrl&quot;: 
                              &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: 
                              &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;ru-ru&quot;}" 
                        data-external-plugin-resources="[]" data-id="id_content" data-type="ckeditortype">
                        </textarea>
                    </div>
                    

                    <div id="file" class="col-3 text-center border p-2"><!--Image-->
                        <h5>Загрузить изображение</h5>
                        <img id="result" class="display_none img-thumbnail rounded mx-auto block">
                        <label id="img_label" class="btn btn-primary btn-lg btn-file">
                            Файл <input type="file" name="img" accept="image/*" id="id_img">
                        </label>
                        
                    </div>

                </div>
                
                
            </div>
        </form>

    </div>


    <script src="{% static 'js/post_create.js' %}">
    </script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "_base.html" %}

{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/post_detail.css' %}">  
{% endblock style %}
   
{% block content %}
    <div id='main'>
        <div id="post" class="container pt-5 pb-5">
            
            <h1>{{ post.title }}</h1>
            <img src="{{ post.img.url }}" class="rounded mx-auto d-block mt-4 mb-5" />
            <div>
                {% autoescape off %}
                    {{ post.content }}
                {% endautoescape %}
                
            </div>

        </div>
    </div>
{% endblock %}